version: "3.9"

services:
  db_payment-service:
    image: postgres:15
    container_name: db_payment_service
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db_payment_service
    ports:
      - "5437:5432"
    volumes:
      - db_payment_service_data:/var/lib/postgresql/data
    networks:
      - minha-rede-compartilhada

  payment-service:
    build:
      context: ../..
      dockerfile: apps/payment-service/Dockerfile
      args:
        SERVICE_PATH: apps/payment-service
    container_name: payment_service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_payment-service:5473/db_payment_service
      SPRING_DATASOURCE_USERNAME: postgres_user
      SPRING_DATASOURCE_PASSWORD: postgres_password
    depends_on:
      - db_payment-service
    networks:
      - minha-rede-compartilhada

volumes:
  db_payment_service_data:
    driver: local

networks:
  minha-rede-compartilhada:
    driver: bridge
