CREATE TABLE IF NOT EXISTS tb_stock
(
    id         INTEGER PRIMARY KEY AUTO_INCREMENT,
    product_id INTEGER   NOT NULL,
    quantity   INTEGER   NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


