version: "3.9"

services:
  db_order-service:
    image: postgres:15
    container_name: db_order_service
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db_order_service
    ports:
      - "5436:5432"
    volumes:
      - db_order_service_data:/var/lib/postgresql/data
    networks:
      - minha-rede-compartilhada

  order-service:
    image: vpereira007/order-service:latest
    container_name: order_service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_order-service:5433/db_order_service
      SPRING_DATASOURCE_USERNAME: postgres_user
      SPRING_DATASOURCE_PASSWORD: postgres_password
    depends_on:
      - db_order-service
    networks:
      - minha-rede-compartilhada

volumes:
  db_order_service_data:
    driver: local

networks:
  minha-rede-compartilhada:
    driver: bridge
