version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - minha-rede-compartilhada

  order-receiver-service:
    image: vpereira007/order-receiver-producer:latest
    container_name: order_receiver_producer
    ports:
      - "8086:8086"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq
    networks:
      - minha-rede-compartilhada

volumes:
  db_order-receiver_service_data:
    driver: local

networks:
  minha-rede-compartilhada:
    driver: bridge
