version: "3.9"

services:
  order-receiver-producer:
    image: vpereira007/order-receiver-producer:latest
    container_name: order_receiver_producer
    ports:
      - "8086:8086"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - minha-rede-compartilhada

volumes:
  db_order-receiver_service_data:
    driver: local

networks:
  minha-rede-compartilhada:
    driver: bridge
