CREATE TABLE IF NOT EXISTS tb_stock
(
    id         INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    product_id INTEGER   NOT NULL,
    quantity   INTEGER   NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


