CREATE TABLE IF NOT EXISTS tb_product
(
    id         INTEGER PRIMARY KEY AUTO_INCREMENT,
    name       VARCHAR(255)   NOT NULL UNIQUE,
    sku        VARCHAR(11)    NOT NULL UNIQUE,
    price      DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);


